service: aws-node-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  timeout: 30
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:Query"
            - "dynamodb:DeleteItem"
            - "dynamodb:Scan"
            - "s3:GetObject"
            - "s3:PutObject"
            - "s3:DeleteObject"
          Resource: "*"
  environment:
    IS_PROD: ${param:IS_PROD}

params:
  default:
    IS_PROD: false
  prod:
    IS_PROD: true
  dev:
    IS_PROD: false
    BASE_URL: "*"

plugins:
  - serverless-offline

functions:
  firstLambda:
    handler: lambdas/index.firstLambda
    iamRoleStatements:
      - Effect: deny
        Action:
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:PutLogEvents
        Resource:
          - arn:aws:logs:*:*:*
    events:
      - http: 
          method: GET
          path: /api/v1/firstLambda
          cors: true